/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gamepadcontrol_Gamepad */

#ifndef _Included_com_gamepadcontrol_Gamepad
#define _Included_com_gamepadcontrol_Gamepad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gamepadcontrol_Gamepad
 * Method:    readData
 * Signature: ()Lcom/gamepadcontrol/Gamepad;
 */
JNIEXPORT jstring JNICALL Java_com_gamepadcontrol_Gamepad_readData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
